theme: dark
git:
  token: "${GIT_TOKEN}"
  repo: repo

# params 字段的值可以在 js 中使用 bblog.GetParams() 获取
params:
  base: ''
  title: Bysir 的博客
  logo: bysir
  friend_links:
    - url: https://blog.ache.fun/
      name: ache
  about:
    - title: 关于博客
      desc: 建立这个博客的目的是分享经验、记录灵感
      content: |
        很久以前就想自己搭建一个博客，记录下自己的东西，但一直没找到合适的工具来搭建博客，故 [写了一个优先满足自己需求的工具](https://github.com/zbysir/bblog)，希望它能承载我所有灵感。
        
        我想在这里记录我灵感和想法，期待它们有一天能给我带来价值。
    - title: 关于我
      desc: 认真打工，努力不打工
      content: |
        喜欢有逻辑的事物，如编程、悬疑电影。对编程略知一二，更多的是在 Web 领域学习；Golang 作为主力语言，也会一点 Vue、React。
        
        做过有趣的事情是将 Golang 与 Vue、React 结合，比如 [这个项目](https://github.com/zbysir/gojsx)，和 [这个](https://github.com/zbysir/go-vue-ssr)。
        
        还想让编程与更多事物结合，如音乐、画画，但还没头绪。
        
        这还有一些项目是我做的 😉：
        
        - [音乐舞台](https://github.com/zbysir/bgm-state)
