#theme: theme/hollow
theme: https://github.com/zbysir/hollow-theme/tree/master/hollow
#theme: file://Users/bysir/front/bysir/hollow-theme/hollow

deploy:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: docs

source:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: master

file:
  img_compression:
    scope: "only_blog" # allï¼šå…¨éƒ¨é™æ€èµ„æºä¸­çš„å›¾ç‰‡ï¼Œonly_blogï¼šå‡ºç°åœ¨æ–‡ç« å¼•ç”¨ä¸­
    width:
    height:
    q:

oss:
  type: qiniu
  access_key: "${QINIU_AK}"
  secret_key: "${QINIU_SK}"
  bucket: bysirblogout
  prefix: blog
  domain: http://blog-static.bysir.top

# å°†ä¼š copy åˆ°æ ¹ç›®å½•
assets:
  - statics

# theme_config å­—æ®µçš„å€¼å¯ä»¥åœ¨ js ä¸­ä½¿ç”¨ bblog.getConfig() è·å–
theme_config:
  base: ''
  title: Bysir çš„åšå®¢
  logo: "bysir"

  fonts:
    # builtin "Noto Serif SC" and 'LXGW WenKai'
    - selector: "body"
      family: "Noto Serif SC"
    - selector: ".hollow-content"
      # è®¾ç½®ä¸ºé»˜è®¤å­—ä½“ï¼Œå‚è€ƒï¼šhttps://zhuanlan.zhihu.com/p/313284552
      family: 'Arial,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","WenQuanYi Micro Hei",sans-serif'

  stack: Tailwindcss + <a href="https://github.com/zbysir/hollow">Hollow</a> + <a href="https://github.com/zbysir/gojsx">Jsx</a>
  footer_links:
    - url: https://github.com/zbysir
      name: GitHub
      icon: GitHub
  links_page: 'pages/links.md'
  about_page: 'pages/about.md'
  gallery:
    items:
      - text: "å¥½æœ‹å‹å©šç¤¼"
        url: "https://blog-static.bysir.top/1667181934593-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/1667181934593-01.jpeg?imageView2/2/w/200"
      - text: "å†ä¸€æ¬¡å»é‡åº†ï¼Œè¿˜æ˜¯å¾ˆå¥½ç©"
        url: "https://blog-static.bysir.top/DSC08656-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC08656-01.jpeg?imageView2/2/w/200"
      - text: "é‡‘é¡¶ï¼Œç«™åœ¨æ‚Ÿç©ºæ‰èƒ½åˆ°è¾¾çš„åœ°æ–¹"
        url: "https://blog-static.bysir.top/DSC06061-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC06061-01.jpeg?imageView2/2/w/200"
      - text: "å·å¤§çš„é“¶æ"
        url: "https://blog-static.bysir.top/DSC05625-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC05625-01.jpeg?imageView2/2/w/200"
      - text: "å“ˆæ ¹è¾¾æ–¯æœ‰ç‚¹ç”œ"
        url: "https://blog-static.bysir.top/IMG_20190215_155754-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/IMG_20190215_155754-01.jpeg?imageView2/2/w/200"
      - text: "æ‰“å¡ç½‘çº¢åŸå¸‚ - é‡åº†"
        url: "https://blog-static.bysir.top/DSC06462-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC06462-01.jpeg?imageView2/2/w/200"
      - text: "æ‰“å¡ç½‘çº¢æ¸¸ä¹å›­ - é‡åº†å¥¥é™¶çºª"
        url: "https://blog-static.bysir.top/DSC06410-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC06410-01.jpeg?imageView2/2/w/200"
      - text: "é­”éƒ½çš„è¿ªå£«å°¼ï¼Œç”±äºä¸æ˜¯å‡æœŸå»çš„ï¼Œäººå°‘ä¸ç”¨æ’é˜Ÿï¼Œæ¯ä¸ªé¡¹ç›®å¯ä»¥ç©å¥½å‡ é"
        url: "https://blog-static.bysir.top/DSC05367-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC05367-01.jpeg?imageView2/2/w/200"
      - text: "éŸ³ä¹èŠ‚è‡³å°‘è¿˜æ˜¯å‚åŠ ä¸€æ¬¡ï¼Œæ„Ÿå—æ„Ÿå—ï¼ˆå»å¬æ°´æ˜Ÿè®°ï¼‰"
        url: "https://blog-static.bysir.top/DSC04833-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC04833-01.jpeg?imageView2/2/w/200"
      - text: "éŸ³ä¹èŠ‚è‡³å°‘è¿˜æ˜¯å‚åŠ ä¸€æ¬¡ï¼Œæ„Ÿå—æ„Ÿå—"
        url: "https://blog-static.bysir.top/DSC04915-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC04915-01.jpeg?imageView2/2/w/200"
      - text: "æ‹¼ä¸€ä¸ªåœ£è¯è£…æ‰®ï¼ˆå…¶å®å–å®¶ç§€å¥½çœ‹å¤šäº†ï¼‰"
        url: "https://blog-static.bysir.top/DSC00553.JPG?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC00553.JPG?imageView2/2/w/200"
      - text: "äº‘å—å¤©æ°”çœŸå¥½ï¼Œè¿˜æƒ³å†å»ä¸€æ¬¡"
        url: "https://blog-static.bysir.top/DSC03185-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC03185-01.jpeg?imageView2/2/w/200"
      - text: "äº‘å—å¤©æ°”çœŸå¥½ï¼Œè¿˜æƒ³å†å»ä¸€æ¬¡"
        url: "https://blog-static.bysir.top/DSC03039-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC03039-01.jpeg?imageView2/2/w/200"
      - text: "æ‹¼äº†ä¸€ä¸‹åˆï¼Œè¿™ç§ä¸œè¥¿åªä¼šä¹°ä¸€æ¬¡"
        url: "https://blog-static.bysir.top/DSC06864.JPG?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC06864.JPG?imageView2/2/w/200"
      - text: "å¤©æ°”å¥½ï¼Œå·¥ä½œéƒ½è½»æ¾ä¸€ç‚¹"
        url: "https://blog-static.bysir.top/IMG_20190611_191053-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/IMG_20190611_191053-01.jpeg?imageView2/2/w/200"
      - text: "æ‰«è¡— - æˆéƒ½"
        url: "https://blog-static.bysir.top/DSC02369-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC02369-01.jpeg?imageView2/2/w/200"
      - text: "å–œæ¬¢è¿™ä¸ªé¢œè‰²"
        url: "https://blog-static.bysir.top/mmexport1555770029553.jpg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/mmexport1555770029553.jpg?imageView2/2/w/200"
      - text: "æ‰«è¡— - æ˜¥ç†™è·¯ï¼Œé‚£æ—¶å€™å¤§å®¶è¿˜ä¸ç”¨æˆ´å£ç½©"
        url: "https://blog-static.bysir.top/DSC02288-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC02288-01.jpeg?imageView2/2/w/200"
      - text: "å®‰é™çš„å‘¨æœ«ï¼Œå®‰é™çš„ğŸŒ§"
        url: "https://blog-static.bysir.top/IMG_20180714_223519-01.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/IMG_20180714_223519-01.jpeg?imageView2/2/w/200"
      - text: "æ²‰æµ¸åœ¨æµ·æ‹‰é²æ— æ³•è‡ªæ‹”"
        url: "https://blog-static.bysir.top/DSC04245-02.jpeg?imageView2/2/w/1200"
        thumb: "https://blog-static.bysir.top/DSC04245-02.jpeg?imageView2/2/w/200"

    title: 'ç…§ç‰‡ä¸æ•…äº‹'
