theme: theme/hollow

deploy:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: docs

source:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: master

file:
  img_compression:
    scope: "only_blog" # allï¼šå…¨éƒ¨é™æ€èµ„æºä¸­çš„å›¾ç‰‡ï¼Œonly_blogï¼šå‡ºç°åœ¨æ–‡ç« å¼•ç”¨ä¸­
    width:
    height:
    q:

oss:
  type: qiniu
  access_key: "${QINIU_AK}"
  secret_key: "${QINIU_SK}"
  bucket: bysirblogout
  prefix: blog
  domain: http://blog-static.bysir.top

# å°†ä¼š copy åˆ°æ ¹ç›®å½•
assets:
  - statics

# theme_config å­—æ®µçš„å€¼å¯ä»¥åœ¨ js ä¸­ä½¿ç”¨ bblog.getConfig() è·å–
theme_config:
  base: ''
  title: Bysir çš„åšå®¢
  logo: "bysir"
  stack: Tailwindcss + <a href="https://github.com/zbysir/hollow">Hollow</a> + <a href="https://github.com/zbysir/gojsx">Jsx</a>
  footer_links:
    - url: https://github.com/zbysir
      name: GitHub
      icon: GitHub
  links_page: 'pages/links.md'
  about:
    - title: å…³äºåšå®¢
      desc: å»ºç«‹è¿™ä¸ªåšå®¢çš„ç›®çš„æ˜¯åˆ†äº«ç»éªŒã€è®°å½•æ€ç»´
      content: |
        å¾ˆä¹…ä»¥å‰å°±æƒ³è‡ªå·±æ­å»ºä¸€ä¸ªåšå®¢ï¼Œè®°å½•ä¸‹è‡ªå·±çš„ä¸œè¥¿ï¼Œä½†ä¸€ç›´æ²¡æ‰¾åˆ°åˆé€‚çš„å·¥å…·æ¥æ­å»ºåšå®¢ï¼Œæ•… [å†™äº†ä¸€ä¸ªä¼˜å…ˆæ»¡è¶³è‡ªå·±éœ€æ±‚çš„å·¥å…·](https://github.com/zbysir/hollow)ï¼Œå¸Œæœ›å®ƒèƒ½æ‰¿è½½æˆ‘æ‰€æœ‰çµæ„Ÿã€‚
        
        æˆ‘æƒ³åœ¨è¿™é‡Œè®°å½•æˆ‘çµæ„Ÿå’Œæƒ³æ³•ï¼Œç§¯å°‘æˆå¤šï¼Œè¿ç‚¹æˆçº¿ã€‚
    - title: å…³äºæˆ‘
      desc: è®¤çœŸæ‰“å·¥ï¼ŒåŠªåŠ›ä¸æ‰“å·¥
      content: |
        å–œæ¬¢æœ‰é€»è¾‘çš„äº‹ç‰©ï¼Œå¦‚ç¼–ç¨‹ã€æ‚¬ç–‘ç”µå½±ã€‚å¯¹ç¼–ç¨‹ç•¥çŸ¥ä¸€äºŒï¼Œæ›´å¤šçš„æ˜¯åœ¨ Web é¢†åŸŸå­¦ä¹ ï¼›Golang ä½œä¸ºä¸»åŠ›è¯­è¨€ï¼Œä¹Ÿä¼šä¸€ç‚¹ Vueã€Reactã€‚
        
        åšè¿‡æœ‰è¶£çš„äº‹æƒ…æ˜¯å°† Golang ä¸ Vueã€React ç»“åˆï¼Œæ¯”å¦‚ [è¿™ä¸ªé¡¹ç›®](https://github.com/zbysir/gojsx)ï¼Œå’Œ [è¿™ä¸ª](https://github.com/zbysir/go-vue-ssr)ã€‚
        
        è¿˜æƒ³è®©ç¼–ç¨‹ä¸â€œè‰ºæœ¯â€ç»“åˆï¼Œå¦‚éŸ³ä¹ã€ç”»ç”»ã€æ¸¸æˆï¼Œæˆ‘ä¹Ÿæƒ³ææè‰ºæœ¯ã€‚
        
        è¿™è¿˜æœ‰ä¸€äº›é¡¹ç›®æ˜¯æˆ‘åšçš„ ğŸ˜‰ï¼š
        
        - [éŸ³ä¹èˆå°](https://github.com/zbysir/bgm-stage)
